# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: false
  branches:
    include:
      - main

pr:
  branches:
    include:
    - main
  paths:
    include: 
      - $(Build.SourcesDirectory)

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validate_ADF_Code
    
    jobs:
    - job: Build_ADF_Code
      
      displayName: 'Validating the ADF Code'
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

  - stage: Test
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
    - job: Tests
      displayName: 'Validating the ADF Code'
      steps:
      - script: echo Hello, world!
        displayName: 'Run a multi-line script'
