on: [push]
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Initialize Terraform
        run: |
          cd tf
          terraform init         

      - name: Plan Terraform
        id: plan
        continue-on-error: true
        run: |
          cd tf
          terraform plan -out=tfplan -no-color 

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: example/
          file: tf/tfplan.json # optional: provide the path for resource to be scanned. This will override the directory if both are provided.
          log_level: DEBUG # optional: set log level. Default WARNING
          config_file: path/this_file
          baseline: tf/.checkov.baseline # optional: Path to a generated baseline file. Will only report results not in the baseline.
          container_user: 1000 # optional: Define what UID and
